export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const GET_KITCHENS = 'GET_KITCHENS';
export const KITCHENS_RECEIVED = 'KITCHENS_RECEIVED';
export const KITCHENS_FAILED = 'KITCHENS_FAILED';

export const CREATE_KITCHENS = 'CREATE_KITCHENS';
export const CREATE_KITCHENS_SUCCESS = 'CREATE_KITCHENS_SUCCESS';
export const CREATE_KITCHENS_FAILED = 'CREATE_KITCHENS_FAILED';

export const EDIT_KITCHEN = 'EDIT_KITCHEN';
export const EDIT_KITCHEN_SUCCESS = 'EDIT_KITCHEN_SUCCESS';
export const EDIT_KITCHEN_FAILED = 'EDIT_KITCHEN_FAILED';

export const KITCHEN_DELETE = 'KITCHEN_DELETE';
export const KITCHEN_DELETE_SUCCESS = 'KITCHEN_DELETE_SUCCESS';
export const KITCHEN_DELETE_FAILED = 'KITCHEN_DELETE_FAILED';

export const GET_RESTAURANT = 'GET_RESTAURANT';
export const RESTAURANT_RECEIVED = 'RESTAURANT_RECEIVED';
export const RESTAURANT_FAILED = 'RESTAURANT_FAILED';

export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const ADD_RESTAURANT_RECEIVED = 'ADD_RESTAURANT_RECEIVED';
export const ADD_RESTAURANT_FAILED = 'ADD_RESTAURANT_FAILED';

export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const EDIT_RESTAURANT_RECEIVED = 'EDIT_RESTAURANT_RECEIVED';
export const EDIT_RESTAURANT_FAILED = 'EDIT_RESTAURANT_FAILED';

export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const DELETE_RESTAURANT_SUCCESS = 'DELETE_RESTAURANT_SUCCESS';

export const GET_REVIEW = 'GET_REVIEW';
export const REVIEW_RECEIVED = 'REVIEW_RECEIVED';
export const REVIEW_FAILED = 'REVIEW_FAILED';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_RECEIVED = 'ADD_REVIEW_RECEIVED';
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';

export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED';

export const GET_ORDER = 'GET_ORDER';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';

export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';

export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED';